baseurl = "/"
languageCode = "en-us"
theme = "paper"
title = "nyando's dev blog"
paginate = 5
relativeURLs = true

[params]
  github = "nyando"
  custom_css = ["css/custom.css"]
  description = "a blog about my personal projects and other software dev topics ~ nyando"
